# prometheus/Dockerfile

# Utiliser l'image officielle Prometheus comme image de base
FROM prom/prometheus:latest

# Copier le fichier de configuration Prometheus dans le conteneur
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Exposer le port Prometheus
EXPOSE 9090

# Démarrer Prometheus avec le fichier de configuration personnalisé
CMD ["--config.file=/etc/prometheus/prometheus.yml"]

