# grafana/Dockerfile

# Utiliser l'image officielle Grafana comme image de base
FROM grafana/grafana:latest

# Copier le fichier de configuration Grafana si nécessaire
# COPY grafana.ini /etc/grafana/grafana.ini

# Exposer le port Grafana
EXPOSE 3001

# Démarrer Grafana
CMD ["grafana-server", "--homepath=/usr/share/grafana", "--config=/etc/grafana/grafana.ini", "cfg:default.paths.data=/var/lib/grafana", "cfg:default.paths.logs=/var/log/grafana", "cfg:default.paths.plugins=/var/lib/grafana/plugins", "cfg:default.paths.provisioning=/etc/grafana/provisioning"]
